// Generated by CoffeeScript 1.8.0
var PreBrunch, exec, sysPath;

sysPath = require('path');

exec = require('child_process').exec;

module.exports = PreBrunch = (function() {
  PreBrunch.prototype.brunchPlugin = true;

  function PreBrunch(config) {
    var _ref;
    this.config = config;
    this.commands = (_ref = this.config.plugins.preBrunch) != null ? _ref : [];
  }

  PreBrunch.prototype.lint = function(generatedFiles) {
    var command, _i, _len, _ref;
    _ref = this.commands;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      command = _ref[_i];
      exec(command, function(error, stdout, stderr) {
        if (stdout) {
          console.log(stdout);
        }
        if (error) {
          console.log(error.message);
        }
        if (stderr) {
          return console.log(stderr);
        }
      });
    }
  };

  return PreBrunch;

})();
