// Generated by CoffeeScript 1.8.0
var PreBrunch, sh, sysPath;

sysPath = require('path');

sh = require('execSync');

module.exports = PreBrunch = (function() {
  PreBrunch.prototype.brunchPlugin = true;

  PreBrunch.prototype.type = 'javascript';

  PreBrunch.prototype.extension = '*';

  PreBrunch.prototype.executed = false;

  function PreBrunch(config) {
    var _ref;
    this.config = config;
    this.commands = (_ref = this.config.plugins.preBrunch) != null ? _ref : [];
  }

  PreBrunch.prototype.lint = function(data, path, callback) {
    var command, _i, _len, _ref;
    if (this.executed) {
      return callback(null);
    }
    _ref = this.commands;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      command = _ref[_i];
      sh.run(command);
    }
    this.executed = true;
    return callback(null);
  };

  PreBrunch.prototype.onCompile = function() {
    this.executed = true;
  };

  return PreBrunch;

})();
